




.build/uno/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/uno/src
	@echo src/sketch.ino
	/usr/local/Cellar/ino/0.3.6/libexec/bin/ino preproc  -o $@ $^


all : .build/uno/src/sketch.cpp
	@true

